### PR TITLE
Allow other events than 'slide' to trigger the update

### PR DESCRIPTION
**Pull request by arambert**
This may be of use for others...
I need this in my app because otherwise the value is not updated when the user only clicks (and do not slide) on the handle

### CODE REVIEW

**Comment by arambert** [comment]
Thank you :smile:

**Comment by swaroopmurthy** [comment]
@arambert What are some other events that are supported? I wanted something that would trigger once the mouse click is released (mouseup)

**Comment by arambert** [comment]
The events available are the ones of jQuery UI slider : http://api.jqueryui.com/slider/#event-change
slidechange, slidecreate, slide (the default), slidestart, slidestop.

**Comment by swaroopmurthy** [comment]
thank you!

**Comment by arambert** [comment]
You're welcome !

**Pull request merged**
